lsst/ap_verify

- README.md
- SConstruct
- config/dataset_config.yaml
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/appipe.py
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/metrics.py
- python/lsst/ap/verify/pipeline.py
- tests/test_args.py
- tests/test_dataset.py
- ups/ap_verify.table
This is an initial implementation for `verify_ap`. It should be equivalent to the pseudocode on [DM-11118](https://jira.lsstcorp.org/browse/DM-11118), except that it has two afterburners and adds explicit support for `lsst.verify`.
The current code does not run because there are no working datasets, so the constructor of `Dataset` always raises. In addition, the stubs in `pipedriver` all raise `NotImplementedError`. However, `test_args` does run, and the main program's command-line parser is functional:
$ python python/lsst/verify/ap/verify_ap.py -h
usage: verify_ap.py [-h] --dataIdString DATAID [-j PROCESSES] [--silent]
--dataset {HiTS} (--output OUTPUT | --rerun OUTPUT)
[--version]
Executes the LSST DM AP pipeline and analyzes its performance using metrics.
optional arguments:
-h, …
> DM-11118: Build stubbed out verify_ap

- python/lsst/ap/verify/dataset.py
- tests/test_dataset.py
Refcats are already stored in a different location in the current dataset system. Defects are currently kept with calibration data, but their handling is controversial and likely to change in the future.
> Add separate directories for refcats and defects.

- .gitignore
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_dataset.py
This PR uses `mkdtemp` to manage tests of `Dataset.make_output_repo`. Because the tested functionality includes directory creation, the modified tests create a second directory inside the temporary.
> DM-11650: Clean up file-based unit tests in ap_verify

- python/lsst/ap/verify/pipeline_driver.py
This PR has two commits. The first (and larger) one simplifies `pipeline_driver` in response to the changes introduced in lsst-dm/ap_pipe#8. The second one implements `_associate` in terms of `ap.pipe.doAssociation`.
> DM-12257: Implement association step in ap_verify

- python/lsst/ap/verify/pipeline_driver.py
`ap_pipe`'s API has been changed in lsst-dm/ap_pipe#10 to assume a repository of coadd templates. This commit changes how `ap_verify` handles difference imaging to compensate.
> DM-11422: Adapt prototype pipeline to use coadds as templates

- README.md
- config/dataset_config.yaml
- python/lsst/ap/verify/measurements/compute_metrics.py
`ap_verify` was not creating measurements because the old config format violated the rules for `Policy`, causing the config object to silently fail (this unhelpful behavior has been reported as [DM-12559](https://jira.lsstcorp.org/browse/DM-12559)). The config format has been altered so that keys are guaranteed to not contain periods.
> DM-12432: Fix timing measurement construction

- demo_run.py
- python/lsst/ap/verify/ap_verify.py
This PR adds a wrapper script that calls `ap_verify` for a specific set of visits and CCDs. The script has the data IDs hard-coded (since I couldn't see another way to extract them pre-ingestion), and has highly special-cased handling of measurement merging. Once DM-12314 is resolved, the script will be unneccessary, as `ap_verify`/`ap_pipe` will be able to internally handle multiple dataIds.
> DM-12535: Wrap ap_verify and run it over HITS dataset

- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/pipeline_driver.py
This PR adds a new decorator, `_MetricsRecovery`, to `pipeline_driver` for handling the shared metrics/job/metadata logic. Despite the discussion on [DM-10779](https://jira.lsstcorp.org/browse/DM-10779?focusedCommentId=84598#comment-84598), I've opted not to replace the existing adapters with an assignment-like syntax. The reasons are twofold:
- neither `ap_verify`'s strategy for handling measurements nor `ap_pipe`'s API are finalized yet, and having explicit adapter functions will make it easier to absorb any changes
- `ap_verify` makes assumptions about how it interacts with `ap_pipe` (for example, any metadata must be in the `getFullMetadata()` format, and `ap_pipe` is expected to internalize details like its system of sub-repositories), and being able to document those assumptions …
> DM-11745: Investigate wrapping external function calls in ap_verify

- doc/lsst.ap.verify/datasets-butler.rst
- doc/lsst.ap.verify/datasets-creation.rst
This PR updates the documentation of the dataset framework to remove unnecessary requirements from the dataset format.
> DM-12851: Determine whether dataset framework can be made generic

- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/datasets-creation.rst
- doc/lsst.ap.verify/datasets-install.rst
- doc/lsst.ap.verify/running.rst
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_args.py
- tests/test_dataset.py
This PR updates the `ap_verify` documentation to comply with the decisions made on [DM-12853](https://jira.lsstcorp.org/browse/DM-12853). Two changes require concurrent updates to source code: renaming `--dataIdString` to `--id` and removing self-setup capability from datasets.
The built documentation is available in [zip format](https://github.com/lsst-dm/ap_verify/files/1696892/docs.zip).
> DM-12853: Review design questions in ap_verify

- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_dataset.py
This PR moves ingestion out of `pipeline_driver` and into a new module called `ingestion`. The new module is responsible for the entire conversion of raws, calibs, and templates from the dataset format into a Butler repository, including some steps that were previously part of the main `ap_verify` module. The repository is then used for all processing by `pipeline_driver`.
Due to API changes, must be merged simultaneously with lsst-dm/ap_pipe#14.
> DM-13451: Make ap_verify responsible for ingestion

- COPYRIGHT
- LICENSE
- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/running.rst
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/config.py
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/measurements/association.py
- python/lsst/ap/verify/measurements/compute_metrics.py
- python/lsst/ap/verify/measurements/profiling.py
- python/lsst/ap/verify/metrics.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/test_args.py
- tests/test_association.py
- tests/test_dataset.py
- tests/test_profiling.py
- tests/test_workspace.py
This PR reworks `ap_verify` to give it more centralized control over the repositories it creates while running. The current strategy is to create three parallel repositories in the directory specified by the user, one for science data, one for calibrations, and one for the output of `ap_pipe`. However, the workspace concept provides enough abstraction that this can be easily changed. In addition, while `ap_pipe` currently requires repository URIs, the system can be easily adapted to pass butlers or datarefs instead.
API changes must be syncedwith lsst-dm/ap_pipe#16.
> DM-13536: Use repositories more idiomatically

- .travis.yml
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- setup.cfg
- tests/test_workspace.py
This is a minimal set of changes needed for `ap_verify` to be able to call `ap_pipe`'s API introduced in lsst-dm/ap_pipe#17. In particular, I did not attempt to change the basic architecture of `pipeline_driver`, as the best design depends on the as-yet nebulous requirements for `ap_verify` (in particular, the desired behavior in the event of pipeline failures).
> DM-13163: Refactor ap_pipe to use CmdLineTask primitives

- python/lsst/ap/verify/metrics.py
- python/lsst/ap/verify/pipeline_driver.py
This pull request adds a command line argument that lets the user specify the metrics output file produced by `ap_verify`. If the argument is not provided, ap_verify reverts to the old behavior.
This PR also fixes a pipeline bug that was introduced by DM-13163.
> DM-13042: allow ap_verify to run under SLURM

- demo_run.py
- python/lsst/__init__.py
- python/lsst/ap/__init__.py
- python/lsst/ap/verify/__init__.py
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/config.py
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/measurements/__init__.py
- python/lsst/ap/verify/measurements/association.py
- python/lsst/ap/verify/measurements/compute_metrics.py
- python/lsst/ap/verify/measurements/profiling.py
- python/lsst/ap/verify/metrics.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/test_args.py
- tests/test_association.py
- tests/test_dataset.py
- tests/test_ingestion.py
- tests/test_profiling.py
- tests/test_workspace.py
This PR cleans up the ingestion unit tests and guarantees that the pipeline driver always passes complete data IDs to `ApPipeTask`. It also removes use of `future` and other Python 2/3 compatibility code.
This PR must be merged after lsst/daf_persistence#93.
> DM-14359: Fix data ID handling in ap_*

- bin.src/ap_verify.py
- bin.src/ingest_dataset.py
- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/running.rst
- python/lsst/ap/verify/ap_verify.py
- tests/test_args.py
This PR creates an ingestion script in (with an unfortunate amount of code duplication) in `ap_verify`. It also fixes some code and documentation errors that crept in through past work.
> DM-13573: Create command-line ingestion script in ap_verify

- python/lsst/ap/verify/ingestion.py
- tests/test_ingestion.py
This PR changes the behavior of `DatasetIngestTask`'s private methods from crashing to raising a specific exception. It also adds a unit test that could not be implemented because of this bug (at least, not while we were still using `testdata_decam`).
> DM-13835: Cannot ingest empty data

- doc/ap_verify/index.rst
- doc/lsst.ap.verify/datasets-creation.rst
- doc/lsst.ap.verify/datasets.rst
This PR makes some miscellaneous updates to the dataset docs in `ap_verify`. No link needed to be added to the documentation introduced in lsst/ap_verify_hits2015#7, as broken links to the `ap_verify_hits2015-package` label were already present.
> DM-14557: Add package docs to datasets

- python/lsst/ap/verify/measurements/association.py
- tests/test_association.py
This PR updates association database queries in `ap_verify` to compensate for lsst-dm/ap_association#17.
> DM-14847: Missing keys in association DB

- doc/lsst.ap.verify/datasets-creation.rst
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/test_driver.py
- tests/test_workspace.py
This PR makes a number of minor improvements to `ap_verify`, adds a unit test suite for the `pipeline_driver` module, and adds code to let `ap_verify`'s instance of `ApPipeTask` use both obs package overrides and any data-specific configs packaged with a dataset. The changes may be easier to understand commit-by-commit.
Note that while this PR would have been much simpler if `pipeline_driver` simply called `ApPipeTask.parseAndRun`, there are some design decisions that need to be made before we can change the driver's architecture. Any such changes are well outside the scope of this ticket.
> DM-14742: Let ap_verify run ap_pipe with dataset-specific configs

- config/dataset_config.yaml
- python/lsst/ap/verify/measurements/association.py
- python/lsst/ap/verify/measurements/compute_metrics.py
- python/lsst/ap/verify/measurements/profiling.py
This PR fixes a systematic error in the metadata keys being used by the `ap.verify.measurements` package (the keys did not get updated when `ap_pipe` was turned into a task). It also broadens the runtime measurer for forward-compatibility with DM-2639.
> DM-14849: Metadata-based metrics not measured

- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/test_driver.py
- tests/test_workspace.py
This PR makes the association database an explicit part of the `ap_verify` workspace. It also fills the `ApPipeConfig` as required by lsst-dm/ap_pipe#29.
> DM-15096: Cannot reuse association database with ApPipeTask reruns

- README.md
- doc/lsst.ap.verify/running.rst
This PR updates the readme to use the modern boilerplate (from [templates](https://github.com/lsst/templates/blob/master/project_templates/stack_package/example_pythononly/README.rst)) and one-sentence-per-line formatting style, plus a brief explanation that `ap_verify` cannot be used by itself (since the dataset system is a significant deviation from normal Stack idioms). The old usage information is deferred to the documentation.
This PR also fixes some misleading text in the command-line examples.
> DM-15138: Incorrect instructions in ap_verify readme

- config/dataset_config.yaml
- doc/lsst.ap.verify/datasets-install.rst
- doc/lsst.ap.verify/datasets.rst
- ups/ap_verify.table
This PR registers `ap_verify_ci_hits2015` with `ap_verify` and adds it to the documentation's list of known datasets. It also updates dataset installation instructions in response to lsst/repos#37.
> DM-15142: Create CI-sized DECam Dataset

- bin/run_ci_dataset.sh
- config/CI-HiTS2015.list
- python/lsst/ap/verify/pipeline_driver.py
This PR introduces a script, `run_ci_dataset.sh`, which encapsulates the environment setup and data ID handling needed to run `ap_verify` on an entire dataset. By analogy with `validate_drp/examples/processData.sh`, the script assumes that the dataset(s) to be run are already downloaded and EUPS set up, and that uploading metric files is the responsibility of the `.groovy` script.
The first commit fixes a fatal bug in `ap_verify` that was, ironically, missed due to lack of CI.
This PR cannot be merged before #40, as the script relies on the latter PR's definition of `CI-HiTS2015`.
> DM-15742: Write shell script to serve as a Jenkins hook

- python/lsst/ap/verify/measurements/association.py
- python/lsst/ap/verify/measurements/compute_metrics.py
This PR changes the namespace of `ap_association` metrics from `association` to `ap_association`. This change is needed to correctly interoperate with the metrics as registered in lsst/verify_metrics#14.
> DM-16319: ap_verify source count metrics do not exist

- config/dataset_config.yaml
This PR adds a metric for extracting timing information from `ApPipeTask`. Note that the metric will not be measurable until some changes to `pipeline_driver` are merged in #49.
> DM-16400: Create a timing metric for ApPipeTask

- .gitignore
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/measurements/compute_metrics.py
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_driver.py
This PR treats metadata-based metrics as a special case of Butler-based metrics, removing `measureFromMetadata` from the `measurements` package's API. It also removes a lot of the vestigial infrastructure that was originally created to juggle metadata, greatly simplifying `pipeline_driver`.
`pipeline_driver` still uses metadata as a workaround for the lack of Butler support in `lsst.verify.Job`; it may be possible to remove this at a later date.
> DM-15901: Access metadata exclusively through Butler

- python/lsst/ap/verify/pipeline_driver.py
- ups/ap_verify.table
@kfindeisen and @jhoblitt I think we could do something like this to get the appropriate metadata in the job.  Does this look reasonable, and how should I test?
> DM-16333: Add Job metadata to the ap job.

- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/measurements/compute_metrics.py
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_driver.py
This PR does some refactoring to remove the `measurements` package's direct dependencies on `Ppdb`, `daf_persistence`, and the `pipeline_driver` module.
> DM-15806: Generalize database handling code

- python/lsst/ap/verify/measurements/__init__.py
- python/lsst/ap/verify/measurements/compute_metrics.py
- python/lsst/ap/verify/measurements/profiling.py
- python/lsst/ap/verify/metrics.py
- tests/test_profiling.py
This PR implements and unit-tests a simple `lsst.verify.compatibility.MetricsTask` (see lsst/verify#30). It also switches computation of timing metrics to the prototypical `lsst.verify.compatibility.MetricsControllerTask`, while handling other metrics using `ap_verify`'s existing system.
> DM-16017: Prototype a metrics-handling Task

- bin/run_ci_dataset.sh
- config/CI-HiTS2015.list
- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/failsafe.rst
- doc/lsst.ap.verify/running.rst
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/measurements/compute_metrics.py
- python/lsst/ap/verify/metrics.py
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_args.py
- tests/test_driver.py
This PR adds multiprocessing support to `ap_verify` by making the `pipeline_driver` module call `ApPipeTask.parseAndRun` instead of `ApPipeTask.runDataRef`. This change requires a complete reorganization of how `ap_verify` passes information from `ap_pipe` to the metrics code, but as a side benefit `ap_verify` no longer needs to parse data IDs itself.
> DM-13887: Let ap_verify process multiple images per instance

- doc/lsst.ap.verify/command-line-reference.rst
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_args.py
This PR allows multiple copies of the `--id` command-line argument (the issue title is an anachronism) to be passed to `ap_verify.py`. No changes are needed to the measurement code, which sees the list of data IDs only in a highly processed form.
While this change was mostly checked with integration tests using `ap_verify_hits2015`, I've also taken the chance to improve the relevant unit tests.
> DM-11698: Let ap_verify support multiple --dataIdString arguments

- config/dataset_config.yaml
- config/default_metrics.py
- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/configuration.rst
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/config.py
- python/lsst/ap/verify/measurements/compute_metrics.py
- python/lsst/ap/verify/measurements/profiling.py
This PR adds the configuration information required by `MetricsControllerTask` as of lsst/verify#33.
> DM-16535: Implement MetricRegistry

- doc/lsst.ap.verify/command-line-reference.rst
- python/lsst/ap/verify/measurements/compute_metrics.py
- python/lsst/ap/verify/measurements/profiling.py
- python/lsst/ap/verify/metrics.py
- tests/test_profiling.py
In lsst/verify#35, `lsst.verify.compatiblity` is renamed to `lsst.verify.gen2tasks`. This PR updates `ap_veify` for this breaking API change.
> DM-17543: Rename lsst.verify.compatibility to gen2tasks

- python/lsst/ap/verify/metrics.py
- python/lsst/ap/verify/workspace.py
- tests/test_workspace.py
This PR modifies the default location of `ap_verify`'s output `Job` files to the workspace created by `--output`. This change is backwards-compatible with scripts that explicitly assign a location.
> DM-17248: ap_verify should create .json files in the workspace by default

- python/lsst/ap/verify/pipeline_driver.py
- tests/test_driver.py
This PR gives the pipeline driver a call to the `make_ppdb.py` script added by lsst/ap_pipe#39, and updates unit tests to require that it be called.
> DM-16606: ap_pipe should not create DB automatically

- doc/lsst.ap.verify/index.rst
The lsst.ap.verify.measurements sub package was dropped in DM-18490.
> Remove lsst.ap.verify.measurements automodapi

- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/ingestion.py
- tests/test_dataset.py
- tests/test_ingestion.py
In light of DM-18739, we needed to update how this package manages that.
> DM-19857: Update for new defects ingestion.

- bin.src/ap_verify.py
- bin.src/ingest_dataset.py
- doc/lsst.ap.verify/command-line-reference.rst
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_driver.py
This PR propagates pipeline status information from the `ApPipeTask` wrapper to the main function, where it can be returned to the shell as if for a command-line task. This fixes a bug where `ap_verify.py` would return 0 after catastrophic pipeline failure and the Jenkins run would be marked as successful.
I think `ap_verify`'s exit code is correctly propagated from `run_ci_dataset.sh` up to Jenkins, but I'm not sure how to test that. :confused:
> DM-20570: Pipeline failure treated as ap_verify success

- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/configuration.rst
- doc/lsst.ap.verify/datasets-butler.rst
- doc/lsst.ap.verify/datasets-creation.rst
- doc/lsst.ap.verify/datasets-install.rst
- doc/lsst.ap.verify/datasets.rst
- doc/lsst.ap.verify/failsafe.rst
- doc/lsst.ap.verify/index.rst
- doc/lsst.ap.verify/new-metrics.rst
- doc/lsst.ap.verify/running.rst
This PR reorganizes the config documentation to make coverage of the metric configs more prominent. The details of what the configs should look like are deferred to [the `MetricsControllerTask` task page](https://pipelines.lsst.io/v/daily/modules/lsst.verify/tasks/lsst.verify.gen2tasks.MetricsControllerTask.html).
The PR also fixes a number of other documentation bugs that were too small to warrant their own issue.
> DM-20251: Improve documentation for how to register metrics with ap_verify

- python/lsst/ap/verify/metrics.py
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_driver.py
This PR adds two command-line arguments:
* `--skip-pipeline` bypasses `ApPipeTask`, leaving the repository in exactly the same state as before (or post-ingestion, if done on the first run of `ap_verify.py`)
* `--skip-existing-metrics` runs `MetricsControllerTask` with the `skipExisting` keyword added in lsst/verify#56.
These two options let users set up partial runs of `ap_verify` for development purposes. I've also optimized `ap_verify`'s metric handling a bit, so it will run faster even in the default case.
> DM-22120: ap_verify scales poorly to large runs

- config/default_dataset_metrics.py
The PR removes the custom config for `PpdbMetricTask` (name change pending; see [DM-22039](https://jira.lsstcorp.org/browse/DM-22039)). After lsst/verify#57, the input dataset type is no longer pipeline-dependent, so it's safe to use the default.
> DM-21877: Create "marker" Butler dataset for PPDB

- config/default_image_metrics.py
This PR changes the default metric configs to use the templates renamed by lsst/verify@e1015bc.
> DM-22641: ap_verify CI broken

- python/lsst/ap/verify/ingestion.py
- tests/test_ingestion.py
This PR fixes a bug where filename filters meant to exclude certain files excluded certain directories instead. It also performs some cleanup of the affected code.
> DM-24523: ap.verify.ingestion._findMatchingFiles excludes directories

- config/dataset_config.yaml
- python/lsst/ap/verify/workspace.py
- tests/test_workspace.py
This PR adds the dataset added by lsst/ap_verify_ci_cosmos_pdr2#1. It also changes all repository paths to absolute to work around various issues in the Gen 2 butler and the Gen 2 to Gen 3 conversion script.
> DM-24259: Create “stub“ Gen2 HSC dataset for CI testing

- python/lsst/ap/verify/ingestion.py
- tests/ingestion/repoTemplate/_mapper
- tests/test_dataset.py
- tests/test_ingestion.py
- ups/ap_verify.table
This PR updates all unit tests to use `ap_verify_testdata` instead of `obs_test` (the ingestion tests rely heavily on details of the specific files in the dataset, and had to be rewritten almost entirely). It also fixes several bugs revealed by the use of ImSim datasets.
> DM-24844: Migrate ap_verify_testdata to obs_lsst

- python/lsst/ap/verify/ingestion.py
- tests/test_ingestion.py
This PR does a bulk removal of all references to "defects" in `DatasetIngestTask`, removing some out-of-date documentation in the process. It then modifies the code to take a (possibly empty) list of curated calib directories, allowing more than one type of curated calib to be ingested at a time.
I ended up sacrificing the code that guards against repeated ingestion of defects. It should be possible to make the check more generic (auto-detecting what the ingested files should look like), but I'm putting that off until [DM-25414](https://jira.lsstcorp.org/browse/DM-25414) to get things merged today.
> DM-25407: ap_verify cannot handle curated crosstalk data in Gen 2

- doc/lsst.ap.verify/command-line-reference.rst
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_args.py
This PR lets callers of `ap_verify.py` use `--id` by itself, with no data ID, without changing the existing behavior when omitting `--id` or using it with a string argument.
> DM-20922: ap_verify can't handle --id with empty argument

- bin/run_ci_dataset.sh
- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/running.rst
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/test_args.py
- tests/test_dataset.py
- tests/test_driver.py
- tests/test_ingestion.py
- tests/test_workspace.py
This PR adds a completely separate Gen 3 channel to the `ap.verify.ingestion` module, with corresponding changes to other `ap_verify` classes. Parallel classes have led to some duplication of code, but it will make migration easier to think about if the Gen 2 and Gen 3 codebases do not depend on each other.
`Dataset` is a Gen-agnostic class, since a downloaded dataset can contain data formatted for both Gen 2 and Gen 3, making the distinction an artificial one. `Workspace` has been given separate classes for Gen 2 and Gen 3 because it was the simplest way to get a clean separation of Gen 2 and 3 elements (conceptually, a workspace is created for a particular processing run, and is therefore either Gen 2 or Gen 3). Of course, `DatasetIngestTask` has completely different Gen 2 and Gen 3 …
> DM-21915: Support Gen 3 ingestion of ap_verify datasets

- bin/run_ci_dataset.sh
This PR fixes a comment that was causing most of the {{ap_verify.py}} command line to be truncated.
> DM-25970: ap_verify CI command line broken

- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/workspace.py
- tests/test_ingestion.py
This PR adds a visit definition subtask to `Gen3DatasetIngestTask`. Calls to `ingest_dataset.py` will now create a repository with fully defined visits, as appropriate for a given instrument.
> DM-26070: Add visit definition to ap_verify

- tests/test_workspace.py
This PR changes the internal directory names in `WorkspaceGen2TestSuite` and `WorkspaceGen3TestSuite` to avoid potential conflicts when both tests are being run simultaneously.
> DM-26265: ap_verify tests use fixed temp directories

- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/failsafe.rst
- doc/lsst.ap.verify/new-metrics.rst
- doc/lsst.ap.verify/running.rst
- pipelines/ApVerify.yaml
- pipelines/MetricsMisc.yaml
- pipelines/MetricsRuntime.yaml
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/test_driver.py
- tests/test_workspace.py
- ups/ap_verify.table
This PR implements the ability to run `ap_verify` entirely in Gen 3. This is a preliminary implementation designed to get something working in CI; see [Jira](https://jira.lsstcorp.org/browse/DM-21919) for a list of ticketed improvements.
This PR is relative to `tickets/DM-26070` to make it easy to see what is changing on this ticket; it must not be merged to `master` before #96.
> DM-21919: Run ap_verify end-to-end in Gen 3

- bin/run_ci_dataset.sh
This PR adds a machine-friendly flag to `run_ci_dataset.sh` that can be passed to `ap_verify.py`.
> DM-24262: Run HSC AP processing in CI using Gen 3

- python/lsst/ap/verify/dataset.py
- tests/test_dataset.py
This PR fixes a bug in how the `ap_verify` dataset is turned into a workspace repository in Gen 3, and fixes the test case that was supposed to enforce the desired behavior.
> DM-26237: Can't rerun ap_verify on same repository in Gen 3

- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/running.rst
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/test_dataset.py
- tests/test_ingestion.py
- tests/test_workspace.py
This PR implements multiprocessing in `Gen3DatasetIngestTask` after adding basic value support to the `Dataset` and `Workspace` classes to make them more unit-test-friendly. This required some refactoring of `ap_verify`'s command-line argument parser.
> DM-25806: Support parallel ap_verify ingestion in Gen 3

- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/running.rst
- tests/test_ingestion.py
Depends on lsst/daf_butler#378
> DM-26738: Rename abstract_filter to band

- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
This PR makes `ap_verify`'s Butler interface more specific by replacing general "all collections" queries with a list of expected collections. Recent changes to calibration handling have added collections that should not be used for user input.
> DM-26953: Update ap_verify system for calibration collections

- python/lsst/ap/verify/dataset.py
This PR creates the `ap_verify` repository without checksums, to ensure that copying the repository is a fast operation (minutes vs. hours, for large repositories). Testing suggests that `daf.butler.Config` silently ignores nonexistent keys, so the new code will work for both file-based and non-file datastores. However, this behavior doesn't seem to be documented anywhere.
> DM-26662: ap_verify import slow in Gen 3

- python/lsst/ap/verify/pipeline_driver.py
- tests/test_driver.py
This PR compensates for several changes to the `ctrl_mpexec` API introduced by lsst/ctrl_mpexec#85.
> DM-27099: Re-bridge ap_verify and ctrl_mpexec

- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/running.rst
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_args.py
This PR adds `--data-query` as a Gen 3-like alternative to `--id`. Currently they can be used interchangeably in both Gen 2 and Gen 3 processing, in the expectation that `--id` will be deprecated along with Gen 2 support.
> DM-26775: Add -d alias to ap_verify CLI

- python/lsst/ap/verify/pipeline_driver.py
- tests/test_driver.py
This PR updates `ap_verify`'s calls to `make_apdb.py` to use the APDB-centric config options introduced in lsst/ap_pipe#62.
> DM-22663: Reimplement make_apdb.py for Gen 3

- doc/lsst.ap.verify/command-line-reference.rst
- python/lsst/ap/verify/pipeline_driver.py
- tests/test_driver.py
This PR lets users override `db_url` when calling `ap_verify`. I've tested the changes with `lsst-pg-devel1` as well as custom SQLite stores.
> DM-26375: Allow databases other than SQLite when running ap_verify

- python/lsst/ap/verify/testUtils.py
- ups/ap_verify.table
This PR compensates for the removal of the `obs_lsst` dependency from lsst/ap_verify_testdata#26 by adding a new dependency, and ensuring the `DataTestCase` base class checks separately for the testdata and the obs package being available.
> DM-26326: Remove obs dependency from ap_verify_testdata and ap_pipe_testdata

- pipelines/ApVerify.yaml
This PR updates the dataset types assumed by the `ApVerify` pipeline, to be consistent with repositories created after merging lsst-dm/ap_verify_dataset_template#19.
> DM-27857: Update ap_verify dataset conversion scripts

- doc/conf.py
- doc/lsst.ap.verify/datasets-install.rst
- doc/lsst.ap.verify/datasets.rst
- doc/lsst.ap.verify/running.rst
This PR updates the `ap_verify` documentation to use the `CI-CosmosPDR2` dataset (which wasn't even listed as a known dataset), as a more user-friendly alternative to HiTS2015.
> DM-27630: Use CI dataset in ap_verify examples

- doc/lsst.ap.verify/command-line-reference.rst
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/test_workspace.py
This PR fixes bugs in both Gen 2 and Gen 3 that prevented `ap_verify` from being rerun for the same data and output workspace, so long as the previous run did not touch the APDB. Supporting multiple runs for the same database is a more challenging problem that would likely require extra checks in `DiaPipelineTask`.
> DM-27325: Can't rerun ap_verify on same repository in Gen 3

- python/lsst/ap/verify/pipeline_driver.py
This PR enforces the running of source association (or, more precisely, `DiaPipelineTask`) in Gen 3 in order of increasing visit ID. Association may still be run in parallel for different detectors within the same visit, and other tasks should be unaffected.
This PR makes no attempt to constrain the Gen 2 processing order, as the tooling needed to do so is completely different.
Depends on lsst/ctrl_mpexec#118.
> DM-12549: ap_pipe must call AssociationTask in a reproducible order

- doc/lsst.ap.verify/running.rst
- python/lsst/ap/verify/__init__.py
- python/lsst/ap/verify/config.py
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/testUtils.py
- python/lsst/ap/verify/workspace.py
This PR adds all classes that were public to a given module to the `ap.verify` `__init__.py` file, and fixes any documentation errors that appeared.
> DM-24806: Lift key ap_verify classes into lsst.ap.verify namespace

- python/lsst/ap/verify/pipeline_driver.py
This PR loads the ap_verify-style dataset's `config/isr.py` if it exists.
This helps ensure gen2 and gen3 isr config parity. In practice, DECam datasets don't have isr configs, but HSC ones do, and for gen2 to work, we need to run ap_verify with the brighter-fatter correction turned off.
> DM-29344: Investigate the CI differences between Gen 2 and 3 in COSMOS field

- config/default_image_metrics.py
- pipelines/MetricsRuntime.yaml
This PR remaps the `MapDiaSourceTime` metric from `diaPipe.diaSourceDpddifier` to `transformDiaSrcCat`, a roughly equivalent(?) task.
> DM-30057: AP timing metrics out of date

- doc/lsst.ap.verify/command-line-reference.rst
- python/lsst/ap/verify/ap_verify.py
- tests/test_args.py
This PR causes `ap_verify.py` and `ingest-dataset.py` to run with Gen 3 rather than Gen 2 when no generation is explicitly provided. It also updates the documentation to be less Gen 2-centric.
> DM-29856: Switch ap_verify.py to Gen 3 by default

- COPYRIGHT
- bin/run_ci_dataset.sh
- pipelines/ApVerifyWithFakes.yaml
This PR fixes some bugs in the existing `Fakes` pipeline and adds a flag to the CI bridge script for choosing a non-default pipeline. This is partly for forward-compatibility with RFC-775, which is expected to make having a single (or pair of) universal pipeline untenable.
> DM-29341: Enable running Fakes in CI for ap_verify

- pipelines/ApVerify.yaml
I successfully ran ap_verify on this ticket branch with the `ap_verify_ci_cosmos_pdr2` dataset.
> DM-29338: Incorporate Gen 3 crosstalk in HiTS runs

- pipelines/ApVerify.yaml
- pipelines/ApVerifyWithFakes.yaml
This PR updates `ApVerify.yaml` to match the changes in lsst/ap_pipe#81, and updates `ApVerifyWithFakes.yaml` with analogous changes.
> DM-30563: ap_verify failing to find dataset type fakes_deepDiff_warpedExp

- pipelines/ApVerifyWithFakes.yaml
This PR updates the fakes pipeline to use the new `pipe.tasks.MatchFakesTask` added in lsst/pipe_tasks#537.
> DM-30776: Move MatchApFakesTask to pipe_tasks

- config/default_image_metrics.py
- pipelines/MetricsMisc.yaml
This PR adds new metrics from lsst/pipe_tasks#512 to the default Gen 2 and Gen 3 `ap_verify` pipelines.
> DM-27032: Create deblended source metric

- python/lsst/ap/verify/pipeline_driver.py
This PR removes the `CliRunner` driver for Gen 3 `ap_verify` and replaces it with a direct `subprocess` call. (Looking back at the discussion that decided to use `CliRunner`, it appears `subprocess` was not even mentioned except as a joke...)
> DM-31180: Force printing of pipeline logs.

- pipelines/ApVerifyWithFakes.yaml
This PR updates the `ApVerifyWithFakes` pipeline so that all metrics in `ip_diffim` and `pipe_tasks` can be expressed in terms of fakes-free datasets. This required some hacking to work around the default AP pipeline's assumptions about which tasks depended on which.
> DM-30349: Don't count fake sources in non-fakes metrics

- pipelines/ApVerifyWithFakes.yaml
This PR corrects an inconsistent metrics config that slipped into `ApVerifyWithFakes` on #135.
> DM-31419: Fix ImageDifference timing in fakes pipeline

- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/pipeline_driver.py
I think in order to switch to python logging we'll have to add a logging.basicConfig and lsst.log forwarding in here somewhere.
> DM-31801: Use lsst prefix for loggers

- bin/run_ci_dataset.sh
This PR stops `run_ci_dataset.sh` from using obsolete `ap_verify.py` flags. This change should have been made as part of #147, where these flags were removed.
The `-g` argument to `run_ci_dataset.sh` is kept, in case we find a need to support something similar in the future.
> DM-33150: Remove --gen flags from CI bridge script.

- COPYRIGHT
- python/lsst/ap/verify/testPipeline.py
- tests/MockApPipe.yaml
- tests/test_driver.py
- tests/test_ingestion.py
- tests/test_testPipeline.py
This PR adds a dummy pipeline that mirrors the form, configuration, and connections of `${AP_PIPE_DIR}/pipelines/ApPipe.yaml`, but is specialized for `ap_verify_testdata` and does no processing besides dataset handling. It then rewrites the tests in `test_driver.py` to make use of the new pipeline.
This change pushes the total unit test run time up to a minute (30 s per individual test), but I don't see any way to reduce this time at present. Because the repository setup for `ap_verify` is fairly complex and doesn't allow for customization hooks, creating an in-memory repository is not practical. I did try to factor the repository setup into `setUpClass`, but this actually _increased_ test run time.
In any case, 20 s of each test's 30 s run time is from running the pipeline itself; this …
> DM-27117: Add dummy pipeline to ap_verify testing

- python/lsst/ap/verify/ingestion.py
This leaves a few unused function arguments in place to reduce the potential for breakage.
> DM-33783: Don't try to parallelize visit definition.

- python/lsst/ap/verify/workspace.py
This PR replaces the previous code that constructed a list of input collections with a single reference to the dataset's `defaults` collection, which is now the source of truth for what inputs are appropriate for a given dataset. This allows for more decentralized handling of optional data types like solar system objects.
> DM-32261: use datasets' defaults collection

- pipelines/ApVerify.yaml
- pipelines/ApVerifyWithFakes.yaml
- pipelines/DarkEnergyCamera/ApVerify.yaml
- pipelines/DarkEnergyCamera/ApVerifyWithFakes.yaml
- pipelines/HyperSuprimeCam/ApVerify.yaml
- pipelines/HyperSuprimeCam/ApVerifyWithFakes.yaml
- pipelines/MetricsForFakes.yaml
- pipelines/MetricsMisc.yaml
This PR refactors the `ApVerifyWithFakes` pipeline to depend on `ApPipeWithFakes` (itself reworked on lsst/ap_pipe#106) instead of `ApVerify`. This change improves consistency with the "base" AP pipeline and avoids some of the contract conflicts that made the previous `ApVerifyWithFakes` more complicated and more brittle than it needed to be.
> DM-32694: Split AP pipeline into ApPipeWithFakes

- python/lsst/ap/verify/ingestion.py
This PR allows `ap_verify` to read datasets whose `preloaded` repo has a registry version other than the latest. This solution involves using an unsafe keyword for `RawIngestTask`, but avoids dataset churn.
This fix is not unit tested, since `ap_verify_testdata` does not have solar system data and therefore does not export exposure records.
> DM-35071: Add support for datasets using old Gen 3 registry versions.

- doc/lsst.ap.verify/datasets-install.rst
- doc/lsst.ap.verify/running.rst
This PR cleans up the docs added in #163 to clearly distinguish between dataset installation, dataset setup, and running `ap_verify`.
> DM-35564: ap_verify docs say datasets should be installed at run-time

- python/lsst/ap/verify/testPipeline.py
- tests/MockApPipe.yaml
- tests/test_testPipeline.py
This PR updates `tests/MockApPipe.yaml` and the tasks within it to mirror the current state of the AP pipeline, particularly the new image differencing system. None of these changes directly affect `ap_verify`, which currently only depends on the config for `DiaPipelineTask`, but they will prevent the tests from breaking when `ImageDifferenceTask` is removed.
> DM-35721: Create mocks of the new image differencing for ap_verify

- pipelines/ApVerify.yaml
- pipelines/ApVerifyWithFakes.yaml
- pipelines/Conversions.yaml
- pipelines/ConversionsForFakes.yaml
This PR adds extra Parquet transformation tasks to both `ap_verify` pipelines. These tasks are not needed (or used) in CI, but make it easier to make plots of `ap_verify` datasets in `analysis_tools`.
> DM-36198: Add parquet transform tasks to ap_verify

- doc/lsst.ap.verify/datasets.rst
This PR removes mention of `ap_verify_hits2015` from the documentation, since it's no longer officially supported.
> DM-36385: Deprecate ap_verify_hits2015 dataset

- doc/lsst.ap.verify/running.rst
We're focusing on CI datasets now, which are small enough that there's not really any point to `--data-query` for most users; they'll want to run the whole thing most of the time, so we should make that the main example we give.
> Remove --data-query from primary example

- doc/lsst.ap.verify/datasets-creation.rst
The `ap_verify` code assumes that the dataset's preloaded repository puts everything except raws in a `defaults/` collection, but this requirement was not documented. This PR fixes that.
> DM-33039: Update dataset specification

- pipelines/MetricsRuntime.yaml
This PR adds pipeline entries for the CPU timing metrics created on lsst/verify_metrics#36.
> DM-37302: Add dedicated metrics for CPU time

- pipelines/ApVerifyWithFakes.yaml
- pipelines/MetricsRuntime.yaml
`ApVerifyWithFakes` has a `transformDiaSrcCatWithFakes` task, but not a `transformDiaSrcCat`. This caused quantum graph errors when `cputiming_transformDiaSrcCat` was added in #180 and configured only for `ApVerify`.
> DM-37807: fix broken ApVerifyWithFakes pipeline

- python/lsst/ap/verify/testPipeline.py
- tests/test_testPipeline.py
This reflects updates to the mocked tasks.
> DM-31924: Update mock tasks to use configurable ID generators.

- doc/lsst.ap.verify/running.rst
Modified the `running.rst` file to also include the instructions for manually fetching and setting up the RB Classifier model packages.
> DM-38981: Add instructions to fetch RB Classifier model packages

- pipelines/LSSTCam-imSim/ApVerify.yaml
- pipelines/LSSTCam-imSim/ApVerifyWithFakes.yaml
plugged rbClassify into dc2 ap_verify
> DM-36743: Add the real-bogus PipelineTask to ap_verify for the DC2 CI dataset

- tests/test_testPipeline.py
The latter will be deprecated in the future.
> DM-39605: Use butler.dimensions rather than butler.registry.dimensions

- doc/lsst.ap.verify/datasets-install.rst
- doc/lsst.ap.verify/running.rst
- python/lsst/ap/verify/pipeline_driver.py
This PR updates our documentation to reflect the fact that now all `ap_verify` datasets are "CI-sized", and patches up some long-standing technical debt in `pipeline_driver`.
> DM-36477: Remove ap_verify_hits2015 dataset

- pipelines/DarkEnergyCamera/ApVerify.yaml
- pipelines/DarkEnergyCamera/ApVerifyWithFakes.yaml
- pipelines/HyperSuprimeCam/ApVerify.yaml
- pipelines/HyperSuprimeCam/ApVerifyWithFakes.yaml
- pipelines/LSSTCam-imSim/ApVerify.yaml
- pipelines/LSSTCam-imSim/ApVerifyWithFakes.yaml
- pipelines/_ingredients/ApVerify.yaml
- pipelines/_ingredients/ApVerifyWithFakes.yaml
This PR merges the `rbClassify` task from instrument-specific pipelines to the base (`_ingredients`) pipeline and removes some configs that are redundant at the instrument level. This leaves the pipelines cleaner and with clearer responsibilities, and will prevent changes to the base pipeline from unexpectedly not working.
Unfortunately, the `ApVerify` pipeline still contains a few elements that should be in `ApPipe` but that shouldn't be moved at this time. These have been marked with TODO comments.
> DM-40210: Clean up ap_pipe and ap_verify pipelines

- .github/pull_request_template.md
- pipelines/_ingredients/ApVerifyWithFakes.yaml
This PR adds a config fix to let `*timing_rbClassify` run in the Fakes pipeline.
****
> DM-40650: RBTransiNet runtime not being measured

- python/lsst/ap/verify/testPipeline.py
- tests/test_testPipeline.py
longTrailedSources needs to be added to the unit test output otherwise ap_verify fails to scons.
> DM-41024: Add longTrailedSources to testPipeline unit tests

- python/lsst/ap/verify/pipeline_driver.py
> DM-38247: Use long-log for ap_verify runs

- pipelines/LSSTCam-imSim/ApVerify.yaml
- pipelines/LSSTCam-imSim/ApVerifyCalibrateImage.yaml
- pipelines/LSSTCam-imSim/ApVerifyWithFakes.yaml
Corrected missed files in original fix. Changed `LSSTCamImSim` to `LSSTCam-imSim` in response to RFC-775.
> DM-33453: Update pipeline references in response to RFC-775. (Hotfix)

- doc/lsst.ap.verify/datasets-creation.rst
- doc/lsst.ap.verify/running.rst
- pipelines/_ingredients/ApVerify.yaml
- pipelines/_ingredients/ApVerifyCalibrateImage.yaml
- pipelines/_ingredients/ApVerifyWithFakes.yaml
- python/lsst/ap/verify/testPipeline.py
- tests/MockApPipe.yaml
- tests/test_testPipeline.py
This PR removes `ApVerify`'s definitions of `rbClassify`, which were added to `ApPipe` on lsst/ap_pipe#156. This change minimizes the degree to which `ApVerify` redefines the AP pipeline instead of augmenting it, fixing a bug where the classifications did not make it into the final `DiaSource` table (see [DM-41147](https://jira.lsstcorp.org/browse/DM-41147)).
****
> DM-42217: Incorporate ModelPackage Butler datasets into ap_verify

- pipelines/_ingredients/MetricsRuntime.yaml
- python/lsst/ap/verify/testPipeline.py
- tests/MockApPipe.yaml
- tests/test_testPipeline.py
> DM-40798: Exclude sky sources from RB classification

- pipelines/_ingredients/ApVerifyWithFakes.yaml
- pipelines/_ingredients/MetricsRuntime.yaml
This PR fixes a couple of configuration errors in `timing_filterDiaSrcCat` and `cputiming_filterDiaSrcCat`.
****
> DM-42818: ApVerifyWithFakes broken in w_2024_06

- pipelines/_ingredients/ApVerify.yaml
- pipelines/_ingredients/ApVerifyWithFakes.yaml
- pipelines/_ingredients/ConversionsForFakes.yaml
- pipelines/_ingredients/MetricsRuntime.yaml
This PR removes all unnecessary without-fakes processing from `ApVerifyWithFakes`, and moves all metrics that are better measured without fakes to `ApVerify`. With no more need to disambiguate, it also removes the `WithFakes` suffix from individual tasks in `ApVerifyWithFakes`.
****
> DM-42419: Break up ApVerify into pure with- and without-fakes pipelines

- pipelines/_ingredients/MetricsRuntime.yaml
This PR adds the timing metric introduced on lsst/ap_pipe#168 to the standard runtime metrics for `ApVerify`. Like all timing metrics, it is not run on `ApVerifyWithFakes`.
****
> DM-40400: Create total AP pipeline timing metric

- pipelines/_ingredients/MetricsRuntime.yaml
- tests/test_testPipeline.py
- updates the unit tests to account for changing doWriteAssociatedSources to True in diaPipe.
- ap_pipe now includes analysis_tools metrics, so make sure they only show up in the ap_verify pipelines once.
****
- [ x] Did you run `ap_verify.py` on at least one of [the standard datasets](https://pipelines.lsst.io/v/daily/modules/lsst.ap.verify/datasets.html#supported-datasets)?
- [x ] Is the Sphinx documentation up-to-date?
> DM-41108: add associated diaSources to diaPipe output

- pipelines/DECam/ApVerify.yaml
- pipelines/HSC/ApVerify.yaml
- pipelines/LSSTCam-imSim/ApVerify.yaml
- pipelines/_ingredients/ApVerify.yaml
Config overrides so alerts are written to disk during CI.
****
- [ X ] Do unit tests pass (`scons` and/or `stack-os-matrix`)?
- [ X ] Did you run `ap_verify.py` on at least one of [the standard datasets](https://pipelines.lsst.io/v/daily/modules/lsst.ap.verify/datasets.html#supported-datasets)?
- [ X ] Is the Sphinx documentation up-to-date?
> DM-30267: Produce three-stamp alerts

- python/lsst/ap/verify/testPipeline.py
- tests/test_testPipeline.py
****
- [ x] Did you run `ap_verify.py` on at least one of [the standard datasets](https://pipelines.lsst.io/v/daily/modules/lsst.ap.verify/datasets.html#supported-datasets)?
- [ x] Is the Sphinx documentation up-to-date?
> DM-43404: Add summaryMetrics to detectAndMeasure output

- python/lsst/ap/verify/testPipeline.py
- tests/test_testPipeline.py
Move spatiallySampledMetrics out of the connections for detectAndMeasure, and add the new pipelineTask that computes them.
****
> DM-43848: Add tests to reflect the new spatially sampled metric Task

- tests/test_testPipeline.py
> DM-43736: Add PSF matching kernel dataset to mock pipeline

- doc/lsst.ap.verify/index.rst
- pipelines/DECam/ApVerify.yaml
- pipelines/DECam/ApVerifyCalibrate.yaml
- pipelines/HSC/ApVerify.yaml
- pipelines/HSC/ApVerifyCalibrate.yaml
- pipelines/LSSTCam-imSim/ApVerify.yaml
- pipelines/LSSTCam-imSim/ApVerifyCalibrate.yaml
- pipelines/_ingredients/ApVerify.yaml
- pipelines/_ingredients/ApVerifyCalibrate.yaml
- pipelines/_ingredients/MetricsMisc.yaml
- pipelines/_ingredients/MetricsMiscCalibrate.yaml
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/MockApPipe.yaml
- tests/test_driver.py
- tests/test_testPipeline.py
- tests/test_workspace.py
This PR modifies the `ap_verify` framework and the metrics pipelines to use new-style configs instead of handling `ApdbConfig` objects directly. It must be merged after lsst/ap_association#210 and lsst/verify#124.
****
> DM-43416: Migrate AP code to external APDB configs

- python/lsst/ap/verify/testPipeline.py
- tests/test_testPipeline.py
> DM-42435: Migrate DM schemas from ccdVisitId to (visit, detector)

- python/lsst/ap/verify/testPipeline.py
- tests/test_testPipeline.py
Remove longTrailedSources from `diaPipe`, change its output to `ArrowAstropy`, and add longTrailedSources to output from `filteredDiaSourceCatalog`
****
- [ x] Did you run `ap_verify.py` on at least one of [the standard datasets](https://pipelines.lsst.io/v/daily/modules/lsst.ap.verify/datasets.html#supported-datasets)?
> DM-41063: Remove trailedSourceFilter and add to filterDiaSourceCatalog

- python/lsst/ap/verify/testPipeline.py
- tests/test_testPipeline.py
Fixing pipeline tests to reflect changes in spatially sampled metrics
****
> DM-43849: Create spatiallySampledMetric to visualize the diffim kernel

- python/lsst/ap/verify/workspace.py
> DM-45209: Fix E721 lint warning (type comparison)

- python/lsst/ap/verify/testPipeline.py
- tests/MockApPipe.yaml
- tests/test_testPipeline.py
****
- [ x] Did you run `ap_verify.py` on at least one of [the standard datasets](https://pipelines.lsst.io/v/daily/modules/lsst.ap.verify/datasets.html#supported-datasets)?
- [ x] Is the Sphinx documentation up-to-date?
> DM-31833: Move LoadDiaCatalogs to standalone pipelineTask 

- pipelines/_ingredients/MetricsRuntime.yaml
****
- [x ] Did you run `ap_verify.py` on at least one of [the standard datasets](https://pipelines.lsst.io/v/daily/modules/lsst.ap.verify/datasets.html#supported-datasets)?
- [x ] Is the Sphinx documentation up-to-date?
> DM-45959: Update timing metrics for LoadDiaCatalogsTask

- pipelines/_ingredients/MetricsRuntime.yaml
This PR fixes a bug introduced in #233 that causes the timing metrics to try to load metadata of the wrong dimensions, causing quantum graph failure.
****
> DM-45959: Fix incorrect metadata dimensions for *timing_loadDiaCatalogs.

- pipelines/DECam/ApVerifyWithFakes.yaml
- pipelines/HSC/ApVerifyWithFakes.yaml
- pipelines/LSSTCam-imSim/ApVerifyWithFakes.yaml
- pipelines/_ingredients/ApVerifyWithFakes.yaml
This PR fixes some consistency issues (including a subtle DECam bug) with `ApVerifyWithFakes`.
****
> DM-43418: Fixes to ApVerify pipelines

- doc/lsst.ap.verify/index.rst
- doc/lsst.ap.verify/limitations.rst
****
- [x ] Do unit tests pass (`scons` and/or `stack-os-matrix`)?
- [x ] Did you run `ap_verify.py` on at least one of [the standard datasets](https://pipelines.lsst.io/v/daily/modules/lsst.ap.verify/datasets.html#supported-datasets)?
- [ x] Is the Sphinx documentation up-to-date?
> DM-42576: Write task to compute predicted positions for an upcoming visit

- python/lsst/ap/verify/ingestion.py
- python/lsst/ap/verify/pipeline_driver.py
- python/lsst/ap/verify/workspace.py
- tests/test_ingestion.py
Using regular expressions to search the Butler for collection names is deprecated in RFC-1040.
****
> DM-46599: Stop using Butler regular expression searches

- pipelines/DECam/ApVerify.yaml
- pipelines/DECam/ApVerifyWithFakes.yaml
- pipelines/HSC/ApVerify.yaml
- pipelines/HSC/ApVerifyWithFakes.yaml
- pipelines/LSSTCam-imSim/ApVerify.yaml
- pipelines/LSSTCam-imSim/ApVerifyWithFakes.yaml
- pipelines/_ingredients/ApVerify.yaml
- pipelines/_ingredients/ApVerifyWithFakes.yaml
- pipelines/_ingredients/MetricsRuntime.yaml
This PR removes the preprocessing tasks from `ApVerify` pipelines. These datasets are now handled by the `ap_verify` data set itself, just like other inputs that are available when raws arrive.
****
> DM-45750: Store new-style ephemerides and APDB catalogs in ap_verify data sets

- pipelines/DECam/ApVerify.yaml
- pipelines/DECam/ApVerifyWithFakes.yaml
- pipelines/HSC/ApVerify.yaml
- pipelines/HSC/ApVerifyWithFakes.yaml
- pipelines/LSSTCam-imSim/ApVerify.yaml
- pipelines/LSSTCam-imSim/ApVerifyWithFakes.yaml
- pipelines/_ingredients/ApVerify.yaml
- pipelines/_ingredients/ApVerifyWithFakes.yaml
> DM-47299: Add the afterburner subset to all of the pipelines

- pipelines/DECam/ApVerify.yaml
- pipelines/HSC/ApVerify.yaml
- pipelines/LSSTCam-imSim/ApVerify.yaml
- pipelines/_ingredients/ApVerify.yaml
- pipelines/_ingredients/MetricsMisc.yaml
- python/lsst/ap/verify/pipeline_driver.py
This PR removes the compatibility config patches added in #224. The config flags themselves were removed by lsst/verify#126 and lsst/ap_association#264.
****
> DM-43419: Remove deprecated fields from DiaPipelineConfig

- pipelines/README.md
This PR removes references to the `processCcd` pipeline subset, which was deprecated on lsst/ap_pipe#218.
****
> DM-48122: Remove ProcessCcd.yaml from ap_pipe

- bin/run_ci_dataset.sh
- doc/lsst.ap.verify/command-line-reference.rst
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/ingestion.py
Update ci run script to take namespace and url for sasquatch upload."
Add optional ChainedDatastore to host SasquatchDatastore
Add new parameters to accomodate for Sasquatch metric upload
****
> DM-46249: Add SasquatchDatastore to enable uploading analysis_tools metrics

- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/ingestion.py
- tests/test_dataset.py
- tests/test_driver.py
- tests/test_ingestion.py
This PR reverts the test changes on #245 (as we should be able to run `ap_verify` without access to Sasquatch) and instead makes the relevant parameters optional. It also adds documentation missing from #244.
****
> DM-46249: Hotfix for Sasquatch parameters and unit tests

- bin/run_ci_dataset.sh
- doc/lsst.ap.verify/command-line-reference.rst
- python/lsst/ap/verify/ap_verify.py
- python/lsst/ap/verify/dataset.py
- python/lsst/ap/verify/ingestion.py
DM-46249: Upload analysis_tools metrics from ap_verify so they can be retrieved in Chronograf
Fix to support optional arguments to ap_verify script, allowing additional keyword,value inputs for dispatching to SasquatchDatastore and Chronograph uploads in CI.
****
> DM-46249-hotfix3 : Upload analysis_tools metrics from ap_verify so they can be retrieved in Chronograf

- doc/lsst.ap.verify/command-line-reference.rst
- doc/lsst.ap.verify/limitations.rst
- pipelines/DECam/ApVerify.yaml
- pipelines/DECam/ApVerifyWithFakes.yaml
- pipelines/HSC/ApVerify.yaml
- pipelines/HSC/ApVerifyWithFakes.yaml
- pipelines/LSSTCam-imSim/ApVerify.yaml
- pipelines/LSSTCam-imSim/ApVerifyWithFakes.yaml
- pipelines/_ingredients/ApVerify.yaml
- pipelines/_ingredients/ApVerifyWithFakes.yaml
- pipelines/_ingredients/Conversions.yaml
- pipelines/_ingredients/ConversionsForFakes.yaml
- pipelines/_ingredients/MetricsMisc.yaml
- pipelines/_ingredients/MetricsRuntime.yaml
- python/lsst/ap/verify/pipeline_driver.py
Renaming the datasets without updating the task defaults wreaks havoc on `ap_verify`, where we have to redefine diaPipe (now associateApdb) in many places. We should create a common config for associateApdb to simplify these definitions!
****
> DM-49875: rename task labels and dataset names for RFC-1088

- python/lsst/ap/verify/pipeline_driver.py
> DM-48980: Update ExecFixupDataId import to pipe_base.

- pipelines/_ingredients/ConversionsForFakes.yaml
Remove fakesType in conversions pipeline
****
> DM-48896: Create pipeline yaml files for DRP with ComCam
